# Generated by Django 6.0.4 on 2026-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_fix_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные')], default='card', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
